schema_version = "1.0.0"

id = "sprytile"
version = "0.6.0"
name = "Sprytile Painter"
tagline = "Build tile based low spec 3D scenes with paint tools"
maintainer = "Jeiel Aranal"
type = "add-on"

website = "https://github.com/ChemiKhazi/Sprytile"

tags = ["Paint", "Mesh", "UV"]

blender_version_min = "4.5.0"

license = [
  "SPDX:MIT",
]

copyright = [
  "2016-2017 Jeiel Dionisio Aranal",
]
